version: '3.8'

services:
  pandidb:
    image: mysql:8.0
    container_name: pandidbc1
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
  pandiwebapp:
    image: pandiflaskmysql:appv1
    build: .
    ports:
      - "3072:5000"
    environment:
      FLASK_ENV: development
      MYSQL_HOST: pandidb
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: testdb
    depends_on:
      - pandidb

#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: example
#       MYSQL_DATABASE: testdb
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
